version: '3'

services:
  postgresql9.5:
    image: postgres:9.5
    ports:
      - "127.0.0.1:54321:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgres
  mysql5.7:
    image: mysql:5.7
    env_file: .env
    ports:
      - "127.0.0.1:33061:3306"
    volumes:
      - ./mysql5_data:/var/lib/mysql
  mysql8.0:
    image: mysql:8.0
    env_file: .env
    ports:
      - "127.0.0.1:33062:3306"
    volumes:
      - ./mysql8_data:/var/lib/mysql
  redis:
    image: redis:3.2.9-alpine
    env_file: .env
    ports:
      - "127.0.0.1:63791:63791"
    volumes:
      - ./redis-data:/data
