version: '3'

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:54321"
    volumes:
      - ./postgresql_data:/var/lib/postgres
  mysql:
    image: mysql:5.7
    ports:
      - "3306:33601"
    volumes:
      - ./mysql_data:/var/lib/mysql
