version: '3'

services:
  postgresql9.5:
    image: postgres:9.5
    ports:
      - "127.0.0.1:54321:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgres
  mysql5.7:
    image: mysql:5.7
    env_file: .env
    ports:
      - "127.0.0.1:33061:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
